# Generated by Django 2.2.17 on 2020-12-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='name',
        ),
    ]
